### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by strangeQuark1041** [strangeQuark1041/samarium#2]
### Bugs

- [ ] Use `mutex`es in Renderer to prevent glitching
- [ ] Set bounding rect for `Renderer::draw_line`

### Features
- [ ] Add [Lennard-Jones](https://en.wikipedia.org/wiki/Lennard-Jones_potential) potential
- [ ] Optimize inter-particle interactions for long distances
